from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Machine',
    'SensorReading',
    'FailureFingerprint',
    'Alert',
    'ChatSession',
    'ChatMessage',
    'WhatIfSimulation',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Machine': {
        'sensorReadings': 'SensorReading',
        'alerts': 'Alert',
        'chatSessions': 'ChatSession',
    },
    'SensorReading': {
        'machine': 'Machine',
    },
    'FailureFingerprint': {
    },
    'Alert': {
        'machine': 'Machine',
    },
    'ChatSession': {
        'machine': 'Machine',
        'messages': 'ChatMessage',
        'simulations': 'WhatIfSimulation',
    },
    'ChatMessage': {
        'session': 'ChatSession',
    },
    'WhatIfSimulation': {
        'session': 'ChatSession',
    },
}

# fmt: on